# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-05 15:28
from __future__ import unicode_literals

from django.db import migrations
import os.path

from django.conf import settings
from django.core.management import call_command

def loaddata(app, schema, fixture_name='initial_data.json'):
    return call_command('loaddata', os.path.join('..', 'fixtures', fixture_name))

class Migration(migrations.Migration):

    dependencies = [
        ('djobberbase', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(loaddata)
    ]
